### ISSUE TITLE
Hyperboloid

### ISSUE THREAD

**Issue by S6savahd** [MartinThoma/LaTeX-examples#50]
Thanks a lot for this nice work - I want to draw upper part of this: https://images.app.goo.gl/7hHN5RJeyrdgHCqL8

would you please point out how to do it.

**Comment by MartinThoma** [comment]
It's been a long time since I created those. You have a better chance of getting an answer on http://tex.stackexchange.com/ (the people there are awesome)

**Comment by S6savahd** [comment]
sure thanks
